name: flutter_map_plugins_example
description: An showcase app for all my flutter_map plugins.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  connectivity_plus: ^7.0.0
  path_provider: ^2.0.15
  dio: ^5.2.0+1
  dio_cache_interceptor: ^4.0.0
  http_cache_drift_store: ^7.0.0
  http_cache_file_store: ^2.0.0
  http_cache_hive_store: ^5.0.0
  sqlite3_flutter_libs: ^0.5.15
  vector_map_tiles: ^9.0.0-beta.8
  vector_tile_renderer: ^6.0.0
  mbtiles: ^0.4.0
  maplibre: ^0.3.0

  flutter_map_cache:
    path: ../flutter_map_cache
  flutter_map_compass:
    path: ../flutter_map_compass
  flutter_map_maplibre:
    path: ../flutter_map_maplibre
  flutter_map_mbtiles:
    path: ../flutter_map_mbtiles
  flutter_map_pmtiles:
    path: ../flutter_map_pmtiles
  vector_map_tiles_mbtiles:
    path: ../vector_map_tiles_mbtiles
  vector_map_tiles_pmtiles:
    path: ../vector_map_tiles_pmtiles

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mbtiles/