name: flutter_map_plugins_example
description: An showcase app for all my flutter_map plugins.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  url_strategy: ^0.2.0

  # flutter_map_cache specific packages
  flutter_map_cache:
    path: ../flutter_map_cache
  connectivity_plus: ^5.0.0
  path_provider: ^2.0.15
  dio: ^5.2.0+1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_db_store: ^5.1.0
  dio_cache_interceptor_file_store: ^1.2.2
  dio_cache_interceptor_hive_store: ^3.2.1
  sqlite3_flutter_libs: ^0.5.15
  vector_map_tiles: ^7.0.1
  vector_tile_renderer: ^5.2.0
  
  vector_map_tiles_mbtiles:
    path: ../vector_map_tiles_mbtiles
  flutter_map_mbtiles:
    path: ../flutter_map_mbtiles
  vector_map_tiles_pmtiles:
    path: ../vector_map_tiles_pmtiles
  flutter_map_pmtiles:
    path: ../flutter_map_pmtiles
  flutter_map_cache:
    path: ../flutter_map_cache

dev_dependencies:
  total_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mbtiles/

