name: flutter_map_cache
description: A slim yet powerful caching plugin for flutter_map tile layers.
version: 1.1.1
repository: https://github.com/josxha/flutter_map_cache
issue_tracker: https://github.com/josxha/flutter_map_cache/issues

topics:
  - flutter-map
  - map
  - dio
  - cache

environment:
  sdk: ^3.0.1

dependencies:
  flutter:
    sdk: flutter
  dio_cache_interceptor: ^3.4.2
  dio: ^5.2.0+1
  flutter_map: ^5.0.0

dev_dependencies:
  total_lints: ^3.0.0
