name: flutter_map_plugins
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - example
  - flutter_map_cache
  - flutter_map_compass
  - flutter_map_maplibre
  - flutter_map_mbtiles
  - flutter_map_pmtiles
#  - vector_map_tiles_mbtiles
#  - vector_map_tiles_pmtiles