name: vector_map_tiles_mbtiles
description: Mapbox MBTiles vector tile provider for vector_map_files / flutter_map that can be used for a 100% offline map.
repository: https://github.com/josxha/flutter_map_plugins
issue_tracker: https://github.com/josxha/flutter_map_plugins/issues
topics: [ flutter-map, vector-map-tiles, map, mbtiles ]
version: 1.2.0

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mbtiles: ^0.4.0
  vector_map_tiles: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.8
  latlong2: ^0.9.0
  flutter_map: ^7.0.0
  very_good_analysis: ^7.0.0
  vector_tile_renderer: ^5.2.0
